package org.khronos.webgl

// WebGL2 doesn't exist in Kotlin/JS standard lib, but just writing it like this allows one to use it apparently
abstract external class WebGL2RenderingContext : WebGLRenderingContextBase, org.w3c.dom.RenderingContext {
  companion object {
    val ACTIVE_ATTRIBUTES: Int /* compiled code */
    val ACTIVE_TEXTURE: Int /* compiled code */
    val ACTIVE_UNIFORMS: Int /* compiled code */
    val ALIASED_LINE_WIDTH_RANGE: Int /* compiled code */
    val ALIASED_POINT_SIZE_RANGE: Int /* compiled code */
    val ALPHA: Int /* compiled code */
    val ALPHA_BITS: Int /* compiled code */
    val ALWAYS: Int /* compiled code */
    val ARRAY_BUFFER: Int /* compiled code */
    val ARRAY_BUFFER_BINDING: Int /* compiled code */
    val ATTACHED_SHADERS: Int /* compiled code */
    val BACK: Int /* compiled code */
    val BLEND: Int /* compiled code */
    val BLEND_COLOR: Int /* compiled code */
    val BLEND_DST_ALPHA: Int /* compiled code */
    val BLEND_DST_RGB: Int /* compiled code */
    val BLEND_EQUATION: Int /* compiled code */
    val BLEND_EQUATION_ALPHA: Int /* compiled code */
    val BLEND_EQUATION_RGB: Int /* compiled code */
    val BLEND_SRC_ALPHA: Int /* compiled code */
    val BLEND_SRC_RGB: Int /* compiled code */
    val BLUE_BITS: Int /* compiled code */
    val BOOL: Int /* compiled code */
    val BOOL_VEC2: Int /* compiled code */
    val BOOL_VEC3: Int /* compiled code */
    val BOOL_VEC4: Int /* compiled code */
    val BROWSER_DEFAULT_WEBGL: Int /* compiled code */
    val BUFFER_SIZE: Int /* compiled code */
    val BUFFER_USAGE: Int /* compiled code */
    val BYTE: Int /* compiled code */
    val CCW: Int /* compiled code */
    val CLAMP_TO_EDGE: Int /* compiled code */
    val COLOR_ATTACHMENT0: Int /* compiled code */
    val COLOR_BUFFER_BIT: Int /* compiled code */
    val COLOR_CLEAR_VALUE: Int /* compiled code */
    val COLOR_WRITEMASK: Int /* compiled code */
    val COMPILE_STATUS: Int /* compiled code */
    val COMPRESSED_TEXTURE_FORMATS: Int /* compiled code */
    val CONSTANT_ALPHA: Int /* compiled code */
    val CONSTANT_COLOR: Int /* compiled code */
    val CONTEXT_LOST_WEBGL: Int /* compiled code */
    val CULL_FACE: Int /* compiled code */
    val CULL_FACE_MODE: Int /* compiled code */
    val CURRENT_PROGRAM: Int /* compiled code */
    val CURRENT_VERTEX_ATTRIB: Int /* compiled code */
    val CW: Int /* compiled code */
    val DECR: Int /* compiled code */
    val DECR_WRAP: Int /* compiled code */
    val DELETE_STATUS: Int /* compiled code */
    val DEPTH_ATTACHMENT: Int /* compiled code */
    val DEPTH_BITS: Int /* compiled code */
    val DEPTH_BUFFER_BIT: Int /* compiled code */
    val DEPTH_CLEAR_VALUE: Int /* compiled code */
    val DEPTH_COMPONENT: Int /* compiled code */
    val DEPTH_COMPONENT16: Int /* compiled code */
    val DEPTH_FUNC: Int /* compiled code */
    val DEPTH_RANGE: Int /* compiled code */
    val DEPTH_STENCIL: Int /* compiled code */
    val DEPTH_STENCIL_ATTACHMENT: Int /* compiled code */
    val DEPTH_TEST: Int /* compiled code */
    val DEPTH_WRITEMASK: Int /* compiled code */
    val DITHER: Int /* compiled code */
    val DONT_CARE: Int /* compiled code */
    val DST_ALPHA: Int /* compiled code */
    val DST_COLOR: Int /* compiled code */
    val DYNAMIC_DRAW: Int /* compiled code */
    val ELEMENT_ARRAY_BUFFER: Int /* compiled code */
    val ELEMENT_ARRAY_BUFFER_BINDING: Int /* compiled code */
    val EQUAL: Int /* compiled code */
    val FASTEST: Int /* compiled code */
    val FLOAT: Int /* compiled code */
    val FLOAT_MAT2: Int /* compiled code */
    val FLOAT_MAT3: Int /* compiled code */
    val FLOAT_MAT4: Int /* compiled code */
    val FLOAT_VEC2: Int /* compiled code */
    val FLOAT_VEC3: Int /* compiled code */
    val FLOAT_VEC4: Int /* compiled code */
    val FRAGMENT_SHADER: Int /* compiled code */
    val FRAMEBUFFER: Int /* compiled code */
    val FRAMEBUFFER_ATTACHMENT_OBJECT_NAME: Int /* compiled code */
    val FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE: Int /* compiled code */
    val FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE: Int /* compiled code */
    val FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL: Int /* compiled code */
    val FRAMEBUFFER_BINDING: Int /* compiled code */
    val FRAMEBUFFER_COMPLETE: Int /* compiled code */
    val FRAMEBUFFER_INCOMPLETE_ATTACHMENT: Int /* compiled code */
    val FRAMEBUFFER_INCOMPLETE_DIMENSIONS: Int /* compiled code */
    val FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT: Int /* compiled code */
    val FRAMEBUFFER_UNSUPPORTED: Int /* compiled code */
    val FRONT: Int /* compiled code */
    val FRONT_AND_BACK: Int /* compiled code */
    val FRONT_FACE: Int /* compiled code */
    val FUNC_ADD: Int /* compiled code */
    val FUNC_REVERSE_SUBTRACT: Int /* compiled code */
    val FUNC_SUBTRACT: Int /* compiled code */
    val GENERATE_MIPMAP_HINT: Int /* compiled code */
    val GEQUAL: Int /* compiled code */
    val GREATER: Int /* compiled code */
    val GREEN_BITS: Int /* compiled code */
    val HIGH_FLOAT: Int /* compiled code */
    val HIGH_INT: Int /* compiled code */
    val IMPLEMENTATION_COLOR_READ_FORMAT: Int /* compiled code */
    val IMPLEMENTATION_COLOR_READ_TYPE: Int /* compiled code */
    val INCR: Int /* compiled code */
    val INCR_WRAP: Int /* compiled code */
    val INT: Int /* compiled code */
    val INT_VEC2: Int /* compiled code */
    val INT_VEC3: Int /* compiled code */
    val INT_VEC4: Int /* compiled code */
    val INVALID_ENUM: Int /* compiled code */
    val INVALID_FRAMEBUFFER_OPERATION: Int /* compiled code */
    val INVALID_OPERATION: Int /* compiled code */
    val INVALID_VALUE: Int /* compiled code */
    val INVERT: Int /* compiled code */
    val KEEP: Int /* compiled code */
    val LEQUAL: Int /* compiled code */
    val LESS: Int /* compiled code */
    val LINEAR: Int /* compiled code */
    val LINEAR_MIPMAP_LINEAR: Int /* compiled code */
    val LINEAR_MIPMAP_NEAREST: Int /* compiled code */
    val LINES: Int /* compiled code */
    val LINE_LOOP: Int /* compiled code */
    val LINE_STRIP: Int /* compiled code */
    val LINE_WIDTH: Int /* compiled code */
    val LINK_STATUS: Int /* compiled code */
    val LOW_FLOAT: Int /* compiled code */
    val LOW_INT: Int /* compiled code */
    val LUMINANCE: Int /* compiled code */
    val LUMINANCE_ALPHA: Int /* compiled code */
    val MAX_COMBINED_TEXTURE_IMAGE_UNITS: Int /* compiled code */
    val MAX_CUBE_MAP_TEXTURE_SIZE: Int /* compiled code */
    val MAX_FRAGMENT_UNIFORM_VECTORS: Int /* compiled code */
    val MAX_RENDERBUFFER_SIZE: Int /* compiled code */
    val MAX_TEXTURE_IMAGE_UNITS: Int /* compiled code */
    val MAX_TEXTURE_SIZE: Int /* compiled code */
    val MAX_VARYING_VECTORS: Int /* compiled code */
    val MAX_VERTEX_ATTRIBS: Int /* compiled code */
    val MAX_VERTEX_TEXTURE_IMAGE_UNITS: Int /* compiled code */
    val MAX_VERTEX_UNIFORM_VECTORS: Int /* compiled code */
    val MAX_VIEWPORT_DIMS: Int /* compiled code */
    val MEDIUM_FLOAT: Int /* compiled code */
    val MEDIUM_INT: Int /* compiled code */
    val MIRRORED_REPEAT: Int /* compiled code */
    val NEAREST: Int /* compiled code */
    val NEAREST_MIPMAP_LINEAR: Int /* compiled code */
    val NEAREST_MIPMAP_NEAREST: Int /* compiled code */
    val NEVER: Int /* compiled code */
    val NICEST: Int /* compiled code */
    val NONE: Int /* compiled code */
    val NOTEQUAL: Int /* compiled code */
    val NO_ERROR: Int /* compiled code */
    val ONE: Int /* compiled code */
    val ONE_MINUS_CONSTANT_ALPHA: Int /* compiled code */
    val ONE_MINUS_CONSTANT_COLOR: Int /* compiled code */
    val ONE_MINUS_DST_ALPHA: Int /* compiled code */
    val ONE_MINUS_DST_COLOR: Int /* compiled code */
    val ONE_MINUS_SRC_ALPHA: Int /* compiled code */
    val ONE_MINUS_SRC_COLOR: Int /* compiled code */
    val OUT_OF_MEMORY: Int /* compiled code */
    val PACK_ALIGNMENT: Int /* compiled code */
    val POINTS: Int /* compiled code */
    val POLYGON_OFFSET_FACTOR: Int /* compiled code */
    val POLYGON_OFFSET_FILL: Int /* compiled code */
    val POLYGON_OFFSET_UNITS: Int /* compiled code */
    val RED: Int /* compiled code */
    val RED_BITS: Int /* compiled code */
    val RENDERBUFFER: Int /* compiled code */
    val RENDERBUFFER_ALPHA_SIZE: Int /* compiled code */
    val RENDERBUFFER_BINDING: Int /* compiled code */
    val RENDERBUFFER_BLUE_SIZE: Int /* compiled code */
    val RENDERBUFFER_DEPTH_SIZE: Int /* compiled code */
    val RENDERBUFFER_GREEN_SIZE: Int /* compiled code */
    val RENDERBUFFER_HEIGHT: Int /* compiled code */
    val RENDERBUFFER_INTERNAL_FORMAT: Int /* compiled code */
    val RENDERBUFFER_RED_SIZE: Int /* compiled code */
    val RENDERBUFFER_STENCIL_SIZE: Int /* compiled code */
    val RENDERBUFFER_WIDTH: Int /* compiled code */
    val RENDERER: Int /* compiled code */
    val REPEAT: Int /* compiled code */
    val REPLACE: Int /* compiled code */
    val RGB: Int /* compiled code */
    val RGB8: Int /* compiled code */
    val RGBA8: Int /* compiled code */
    val RGB32F: Int /* compiled code */
    val RGBA32F: Int /* compiled code */
    val RGBA32UI: Int /* compiled code */
    val R32F: Int /* compiled code */
    val RGB565: Int /* compiled code */
    val RGB5_A1: Int /* compiled code */
    val RGBA: Int /* compiled code */
    val RGBA_INTEGER: Int /* compiled code */
    val RGBA4: Int /* compiled code */
    val SAMPLER_2D: Int /* compiled code */
    val SAMPLER_CUBE: Int /* compiled code */
    val SAMPLES: Int /* compiled code */
    val SAMPLE_ALPHA_TO_COVERAGE: Int /* compiled code */
    val SAMPLE_BUFFERS: Int /* compiled code */
    val SAMPLE_COVERAGE: Int /* compiled code */
    val SAMPLE_COVERAGE_INVERT: Int /* compiled code */
    val SAMPLE_COVERAGE_VALUE: Int /* compiled code */
    val SCISSOR_BOX: Int /* compiled code */
    val SCISSOR_TEST: Int /* compiled code */
    val SHADER_TYPE: Int /* compiled code */
    val SHADING_LANGUAGE_VERSION: Int /* compiled code */
    val SHORT: Int /* compiled code */
    val SRC_ALPHA: Int /* compiled code */
    val SRC_ALPHA_SATURATE: Int /* compiled code */
    val SRC_COLOR: Int /* compiled code */
    val STATIC_DRAW: Int /* compiled code */
    val STENCIL_ATTACHMENT: Int /* compiled code */
    val STENCIL_BACK_FAIL: Int /* compiled code */
    val STENCIL_BACK_FUNC: Int /* compiled code */
    val STENCIL_BACK_PASS_DEPTH_FAIL: Int /* compiled code */
    val STENCIL_BACK_PASS_DEPTH_PASS: Int /* compiled code */
    val STENCIL_BACK_REF: Int /* compiled code */
    val STENCIL_BACK_VALUE_MASK: Int /* compiled code */
    val STENCIL_BACK_WRITEMASK: Int /* compiled code */
    val STENCIL_BITS: Int /* compiled code */
    val STENCIL_BUFFER_BIT: Int /* compiled code */
    val STENCIL_CLEAR_VALUE: Int /* compiled code */
    val STENCIL_FAIL: Int /* compiled code */
    val STENCIL_FUNC: Int /* compiled code */
    val STENCIL_INDEX: Int /* compiled code */
    val STENCIL_INDEX8: Int /* compiled code */
    val STENCIL_PASS_DEPTH_FAIL: Int /* compiled code */
    val STENCIL_PASS_DEPTH_PASS: Int /* compiled code */
    val STENCIL_REF: Int /* compiled code */
    val STENCIL_TEST: Int /* compiled code */
    val STENCIL_VALUE_MASK: Int /* compiled code */
    val STENCIL_WRITEMASK: Int /* compiled code */
    val STREAM_DRAW: Int /* compiled code */
    val SUBPIXEL_BITS: Int /* compiled code */
    val TEXTURE: Int /* compiled code */
    val TEXTURE0: Int /* compiled code */
    val TEXTURE1: Int /* compiled code */
    val TEXTURE10: Int /* compiled code */
    val TEXTURE11: Int /* compiled code */
    val TEXTURE12: Int /* compiled code */
    val TEXTURE13: Int /* compiled code */
    val TEXTURE14: Int /* compiled code */
    val TEXTURE15: Int /* compiled code */
    val TEXTURE16: Int /* compiled code */
    val TEXTURE17: Int /* compiled code */
    val TEXTURE18: Int /* compiled code */
    val TEXTURE19: Int /* compiled code */
    val TEXTURE2: Int /* compiled code */
    val TEXTURE20: Int /* compiled code */
    val TEXTURE21: Int /* compiled code */
    val TEXTURE22: Int /* compiled code */
    val TEXTURE23: Int /* compiled code */
    val TEXTURE24: Int /* compiled code */
    val TEXTURE25: Int /* compiled code */
    val TEXTURE26: Int /* compiled code */
    val TEXTURE27: Int /* compiled code */
    val TEXTURE28: Int /* compiled code */
    val TEXTURE29: Int /* compiled code */
    val TEXTURE3: Int /* compiled code */
    val TEXTURE30: Int /* compiled code */
    val TEXTURE31: Int /* compiled code */
    val TEXTURE4: Int /* compiled code */
    val TEXTURE5: Int /* compiled code */
    val TEXTURE6: Int /* compiled code */
    val TEXTURE7: Int /* compiled code */
    val TEXTURE8: Int /* compiled code */
    val TEXTURE9: Int /* compiled code */
    val TEXTURE_2D: Int /* compiled code */
    val TEXTURE_BINDING_2D: Int /* compiled code */
    val TEXTURE_BINDING_CUBE_MAP: Int /* compiled code */
    val TEXTURE_CUBE_MAP: Int /* compiled code */
    val TEXTURE_CUBE_MAP_NEGATIVE_X: Int /* compiled code */
    val TEXTURE_CUBE_MAP_NEGATIVE_Y: Int /* compiled code */
    val TEXTURE_CUBE_MAP_NEGATIVE_Z: Int /* compiled code */
    val TEXTURE_CUBE_MAP_POSITIVE_X: Int /* compiled code */
    val TEXTURE_CUBE_MAP_POSITIVE_Y: Int /* compiled code */
    val TEXTURE_CUBE_MAP_POSITIVE_Z: Int /* compiled code */
    val TEXTURE_MAG_FILTER: Int /* compiled code */
    val TEXTURE_MIN_FILTER: Int /* compiled code */
    val TEXTURE_WRAP_S: Int /* compiled code */
    val TEXTURE_WRAP_T: Int /* compiled code */
    val TRIANGLES: Int /* compiled code */
    val TRIANGLE_FAN: Int /* compiled code */
    val TRIANGLE_STRIP: Int /* compiled code */
    val UNPACK_ALIGNMENT: Int /* compiled code */
    val UNPACK_COLORSPACE_CONVERSION_WEBGL: Int /* compiled code */
    val UNPACK_FLIP_Y_WEBGL: Int /* compiled code */
    val UNPACK_PREMULTIPLY_ALPHA_WEBGL: Int /* compiled code */
    val UNSIGNED_BYTE: Int /* compiled code */
    val UNSIGNED_INT: Int /* compiled code */
    val UNSIGNED_SHORT: Int /* compiled code */
    val UNSIGNED_SHORT_4_4_4_4: Int /* compiled code */
    val UNSIGNED_SHORT_5_5_5_1: Int /* compiled code */
    val UNSIGNED_SHORT_5_6_5: Int /* compiled code */
    val VALIDATE_STATUS: Int /* compiled code */
    val VENDOR: Int /* compiled code */
    val VERSION: Int /* compiled code */
    val VERTEX_ATTRIB_ARRAY_BUFFER_BINDING: Int /* compiled code */
    val VERTEX_ATTRIB_ARRAY_ENABLED: Int /* compiled code */
    val VERTEX_ATTRIB_ARRAY_NORMALIZED: Int /* compiled code */
    val VERTEX_ATTRIB_ARRAY_POINTER: Int /* compiled code */
    val VERTEX_ATTRIB_ARRAY_SIZE: Int /* compiled code */
    val VERTEX_ATTRIB_ARRAY_STRIDE: Int /* compiled code */
    val VERTEX_ATTRIB_ARRAY_TYPE: Int /* compiled code */
    val VERTEX_SHADER: Int /* compiled code */
    val VIEWPORT: Int /* compiled code */
    val ZERO: Int /* compiled code */
  }
}
